[workspace]
authors = ["ousttrue <ousttrue@gmail.com>"]
channels = ["robostack-humble", "conda-forge"]
name = "my_ros2_project"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
build = {cmd = "colcon build --symlink-install", inputs = ["src"]}
# pixi run build --cmake-args -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo

[activation]
scripts = ["install/setup.bat"]

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
ros-humble-ament-cmake-auto = ">=1.3.11,<2"
compilers = ">=1.10.0,<2"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=4.0.3,<5"
ninja = ">=1.13.1,<2"
ros-humble-turtlesim = ">=1.4.2,<2"
setuptools = "<=58.2.0"
